### ISSUE TITLE
About string.csv

### ISSUE THREAD

**Issue by LezaiYa** [vdpcool/TOHEK#2]
![image](https://github.com/vdpcool/TOHEK/assets/110912016/95ed590f-a426-4bbf-8642-26c13eabd58d)

What is all this Chinese, how come it's all the same, lol (curious to ask)

**Comment by vdpcool** [comment]
> ![image](https://user-images.githubusercontent.com/110912016/263438873-95ed590f-a426-4bbf-8642-26c13eabd58d.png)
> 
> What is all this Chinese, how come it's all the same, lol (curious to ask)

Um yes, im lazy to use google trans.
Also i was copied the old line then make a new line for new addon.

**Comment by LezaiYa** [comment]
> > ![image](https://user-images.githubusercontent.com/110912016/263438873-95ed590f-a426-4bbf-8642-26c13eabd58d.png)
> > What is all this Chinese, how come it's all the same, lol (curious to ask)
> 
> Um yes, im lazy to use google trans. Also i was copied the old line then make a new line for new addon.

lol
